-- Step A: Calculate raw Recency, Frequency, and Monetary metrics
WITH rfm_base AS (
    SELECT 
        customer_id,
        -- Recency: Days between the customer's last purchase and the current snapshot date (July 29, 2026)
        EXTRACT(DAY FROM ('2026-07-29 00:00:00'::timestamp - MAX(invoice_date))) AS recency,
        -- Frequency: Total distinct orders placed
        COUNT(DISTINCT invoice_no) AS frequency,
        -- Monetary: Total revenue generated by the customer
        SUM(quantity * unit_price) AS monetary
    FROM online_retail
    WHERE customer_id IS NOT NULL 
    GROUP BY customer_id
),

-- Step B: Use NTILE to assign a score from 1 to 5 for each metric
rfm_scores AS (
    SELECT 
        customer_id,
        recency,
        frequency,
        monetary,
        -- Low recency days are good, so we invert sorting using DESC
        NTILE(5) OVER (ORDER BY recency DESC) AS r_score,
        NTILE(5) OVER (ORDER BY frequency ASC) AS f_score,
        NTILE(5) OVER (ORDER BY monetary ASC) AS m_score
    FROM rfm_base
)

-- Step C: Assign readable marketing personas based on custom score boundaries
SELECT 
    customer_id,
    recency,
    frequency,
    monetary,
    CONCAT(r_score, f_score, m_score) AS rfm_string,
    CASE 
        WHEN r_score >= 4 AND f_score >= 4 AND m_score >= 4 THEN 'VIP / Champion'
        WHEN r_score >= 3 AND f_score >= 3 THEN 'Loyal Customer'
        WHEN r_score >= 4 AND f_score <= 2 THEN 'New Customer'
        WHEN r_score <= 2 AND f_score >= 3 THEN 'At Risk / Cannot Lose'
        ELSE 'Hibernating / Lost'
    END AS customer_segment
FROM rfm_scores
ORDER BY monetary DESC;